### ISSUE TITLE
Update Share Tech Mono with a fixed version (ligature issue) 

### ISSUE THREAD

**Issue by AndydeCleyre** [w0ng/googlefontdirectory#13]
You can see the official bug report at https://code.google.com/p/googlefontdirectory/issues/detail?id=202

Certain letter combinations ('fl', 'fi') show up as single dots.

Comment 3 describes how to fix the issue with the font file using fontforge, comment 5 links to a blog post linking to a fixed version hosted on dropbox. These fixes have been available, but neglected by the Google repo.

Please consider updating the font in this repo.

**Comment by w0ng** [comment]
Sorry, this repo is a intended to be a clone of Google's built fonts.
Users should use Google's official hg repo to build from source.
